local Tali = LibStub("AceAddon-3.0"):GetAddon("Tali")

function Tali:PriorityTable ()
	local tablePrio = {}
	tablePrio = {
	-- any stat with two or more words that needs to be compaired  needs ["this type"] = value of format
	{class = "Death Knight", spec = "Blood", Stamina = 5, Strength = 5, Agility = 0, Intellect = 0, Mastery = 1.4, ["Critical Strike"] = 1.14, Haste = 4.27, Multistrike = 4.63, Versatility = 3.56, Spirit = 0, Armor = 5, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	{class = "Death Knight", spec = "Frost", Stamina = 0, Strength = 5, Agility = 0, Intellect = 0, Mastery = 3.46, ["Critical Strike"] = 2.78, Haste = 2.66, Multistrike = 3.11, Versatility = 2.99, Spirit = 0, Armor = 0, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},	
	{class = "Death Knight", spec = "Unholy", Stamina = 0, Strength = 5, Agility = 0, Intellect = 0, Mastery = 3.41, ["Critical Strike"] = 2.92, Haste = 2.43, Multistrike = 3.47, Versatility = 2.75, Spirit = 0, Armor = 0, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},

	{class = "Druid", spec = "Balance", Stamina = 0, Strength = 0, Agility = 0, Intellect = 5, Mastery = 3.07, ["Critical Strike"] = 3.08, Haste = 3.05, Multistrike = 3.04, Versatility = 2.74, Spirit = 0, Armor = 0,  prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	{class = "Druid", spec = "Feral", Stamina = 0, Strength = 0, Agility = 5, Intellect = 0, Mastery = 2.81, ["Critical Strike"] = 3.22, Haste = 2.97, Multistrike = 3.12, Versatility = 2.9, Spirit = 0, Armor = 0,  prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	{class = "Druid", spec = "Guardian", Stamina = 5, Strength = 0, Agility = 5, Intellect = 0, Mastery = 7.46, ["Critical Strike"] = 0.14, Haste = 1.17, Multistrike = 0.39, Versatility = 5.82, Spirit = 0, Armor = 5,  prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	{class = "Druid", spec = "Restoration", Stamina = 0, Strength = 0, Agility = 0, Intellect = 5, Mastery = 3.14, ["Critical Strike"] = 2.84, Haste = 3.21, Multistrike = 3.06, Versatility = 2.76, Spirit = 3, Armor = 0,  prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	
	{class = "Hunter", spec = "Beast Mastery", Stamina = 0, Strength = 0, Agility = 4.61, Intellect = 0, Mastery = 10.70, ["Critical Strike"] = 12.48, Haste = 11.28, Multistrike = 0, Versatility = 10.10, Spirit = 0, Armor = 0, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	{class = "Hunter", spec = "Marksmanship", Stamina = 0, Strength = 0, Agility = 5, Intellect = 0, Mastery = 2.75, ["Critical Strike"] = 3.11, Haste = 2.76, Multistrike = 3.33, Versatility = 3.05, Spirit = 0, Armor = 0, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	{class = "Hunter", spec = "Survival", Stamina = 0, Strength = 0, Agility = 3.71, Intellect = 0, Mastery = 6.12, ["Critical Strike"] = 8.62, Haste = 12.82, Multistrike = 3.55, Versatility = 7.87, Spirit = 0, Armor = 0, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	
	{class = "Mage", spec = "Arcane", Stamina = 0, Strength = 0, Agility = 0, Intellect = 5, Mastery = 3.33, ["Critical Strike"] = 2.93, Haste = 2.93, Multistrike = 3.04, Versatility = 2.75, Spirit = 0, Armor = 0, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	{class = "Mage", spec = "Fire", Stamina = 0, Strength = 0, Agility = 0, Intellect = 5, Mastery = 3.02, ["Critical Strike"] = 3.65, Haste = 2.85, Multistrike = 2.89, Versatility = 2.58, Spirit = 0, Armor = 0, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	{class = "Mage", spec = "Frost", Stamina = 0, Strength = 0, Agility = 0, Intellect = 5, Mastery = 2.66, ["Critical Strike"] = 3.1, Haste = 2.72, Multistrike = 3.52, Versatility = 3.02, Spirit = 0, Armor = 0, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},	
	
	{class = "Monk", spec = "Brewmaster", Stamina = 5, Strength = 0, Agility = 5, Intellect = 0, Mastery = 5.67, ["Critical Strike"] = 1.65, Haste = 2.66, Multistrike = 1.3, Versatility = 3.73, Spirit = 0, Armor = 5, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	{class = "Monk", spec = "Mistweaver", Stamina = 0, Strength = 0, Agility = 0, Intellect = 5, Mastery = 2.63, ["Critical Strike"] = 3.24, Haste = 2.78, Multistrike = 3.39, Versatility = 2.94, Spirit = 3, Armor = 0, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	{class = "Monk", spec = "Windwalker DW", Stamina = 0, Strength = 0, Agility = 5, Intellect = 0, Mastery = 2.21, ["Critical Strike"] = 3.19, Haste = 3.02, Multistrike = 3.36, Versatility = 3.21, Spirit = 0, Armor = 0, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	
	{class = "Priest", spec = "Discipline", Stamina = 0, Strength = 0, Agility = 0, Intellect = 5, Mastery = 2.69, ["Critical Strike"] = 2.69, Haste = 3.15, Multistrike = 0, Versatility = 2.69, Spirit = 0, Armor = 0, prio = 0, Leech = 6, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 2},
	{class = "Priest", spec = "Holy", Stamina = 0, Strength = 0, Agility = 0, Intellect = 5, Mastery = 3.15, ["Critical Strike"] = 3.10, Haste = 2.69, Multistrike = 0, Versatility = 2.84, Spirit = 0, Armor = 0, prio = 0, Leech = 6, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 2},
	{class = "Priest", spec = "Shadow", Stamina = 0, Strength = 0, Agility = 0, Intellect = 5, Mastery = 3.22, ["Critical Strike"] = 2.93, Haste = 3.12, Multistrike = 0, Versatility = 2.77, Spirit = 0, Armor = 0, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 2},	
	
	{class = "Rogue", spec = "Assassination", Stamina = 0, Strength = 0, Agility = 5, Intellect = 0, Mastery = 3.05, ["Critical Strike"] = 3.07, Haste = 2.85, Multistrike = 3.16, Versatility = 2.89, Spirit = 0, Armor = 0, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},	
	{class = "Rogue", spec = "Combat", Stamina = 0, Strength = 0, Agility = 5, Intellect = 0, Mastery = 2.97, ["Critical Strike"] = 2.88, Haste = 3.18, Multistrike = 3.1, Versatility = 2.87, Spirit = 0, Armor = 0, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	{class = "Rogue", spec = "Subtlety", Stamina = 0, Strength = 0, Agility = 5, Intellect = 0, Mastery = 3.21, ["Critical Strike"] = 2.89, Haste = 2.75, Multistrike = 3.31, Versatility = 2.83, Spirit = 0, Armor = 0, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	
	{class = "Shaman", spec = "Elemental", Stamina = 0, Strength = 0, Agility = 0, Intellect = 5, Mastery = 2.89, ["Critical Strike"] = 3.08, Haste = 2.96, Multistrike = 3.28, Versatility = 2.8, Spirit = 0, Armor = 0, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	{class = "Shaman", spec = "Enhancement", Stamina = 0, Strength = 0, Agility = 5, Intellect = 0, Mastery = 3.04, ["Critical Strike"] = 2.93, Haste = 2.98, Multistrike = 3.12, Versatility = 2.91, Spirit = 0, Armor = 0, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	{class = "Shaman", spec = "Restoration", Stamina = 0, Strength = 0, Agility = 0, Intellect = 5, Mastery = 3.15, ["Critical Strike"] = 3.3, Haste = 2.69, Multistrike = 3, Versatility = 2.84, Spirit = 3, Armor = 0, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	
	{class = "Warlock", spec = "Affliction", Stamina = 0, Strength = 0, Agility = 0, Intellect = 5, Mastery = 3.24, ["Critical Strike"] = 2.95, Haste = 3.08, Multistrike = 2.97, Versatility = 2.78, Spirit = 0, Armor = 0, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	{class = "Warlock", spec = "Demonology", Stamina = 0, Strength = 0, Agility = 0, Intellect = 5, Mastery = 2.96, ["Critical Strike"] = 3.02, Haste = 3.25, Multistrike = 3, Versatility = 2.78, Spirit = 0, Armor = 0, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	{class = "Warlock", spec = "Destruction", Stamina = 0, Strength = 0, Agility = 0, Intellect = 5, Mastery = 2.95, ["Critical Strike"] = 3.12, Haste = 2.96, Multistrike = 3.07, Versatility = 2.88, Spirit = 0, Armor = 0, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},

	{class = "Warrior", spec = "Arms", Stamina = 0, Strength = 5, Agility = 0, Intellect = 0, Mastery = 2.94, ["Critical Strike"] = 3.45, Haste = 2.8, Multistrike = 2.99, Versatility = 2.84, Spirit = 0, Armor = 0, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	{class = "Warrior", spec = "Fury", Stamina = 0, Strength = 5, Agility = 0, Intellect = 0, Mastery = 3.02, ["Critical Strike"] = 3.26, Haste = 2.8, Multistrike = 3.21, Versatility = 2.73, Spirit = 0, Armor = 0, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	{class = "Warrior", spec = "Protection", Stamina = 5, Strength = 5, Agility = 0, Intellect = 0, Mastery = 3.6, ["Critical Strike"] = 3.74, Haste = 0.7, Multistrike = 1.74, Versatility = 5.2, Spirit = 0, Armor = 5, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	{class = "Warrior", spec = "Gladiator", Stamina = 0, Strength = 5, Agility = 0, Intellect = 0, Mastery = 2.73, ["Critical Strike"] = 3.26, Haste = 3.21, Multistrike = 3, Versatility = 2.79, Spirit = 0, Armor = 2.5, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	
	{class = "Paladin", spec = "Protection", Stamina = 1.38, Strength = 0.65, Agility = 0, Intellect = 0, Mastery = 1.86, ["Critical Strike"] = 1.13, Haste = 1.93, Multistrike = 0.85, Versatility = 2.07, Spirit = 0, Armor = 3.5, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	{class = "Paladin", spec = "Retribution", Stamina = 0, Strength = 18.02, Agility = 0, Intellect = 0, Mastery = 21.94, ["Critical Strike"] = 22.53, Haste = 26.43, Multistrike = 0, Versatility = 23.28, Spirit = 0, Armor = 0, prio = 0, Leech = 0, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	{class = "Paladin", spec = "Holy", Stamina = 0, Strength = 0, Agility = 0, Intellect = 1, Mastery = 1.38, ["Critical Strike"] = 1.73, Haste = 1.33, Multistrike = 0, Versatility = 1.52, Spirit = 0, Armor = 0, prio = 0, Leech = 1.54, Avoidance = 0, Speed = 0, ["Bonus Armor"] = 0, ["Attack Power"] = 0, ["Spell Power"] = 0},
	}

	return tablePrio
end